// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMe.DataAccess;

#nullable disable

namespace ProMe.DataAccess.Migrations
{
    [DbContext(typeof(ProMeDBContext))]
    [Migration("20230708171018_campaigns_202307082009")]
    partial class campaigns_202307082009
    {
        /// <inheritdoc />
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProMe.DataAccess.Models.Contact", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .HasMaxLength(254)
                    .HasColumnType("nvarchar(254)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(350)
                    .HasColumnType("nvarchar(350)");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(25)
                    .HasColumnType("nvarchar(25)");

                b.HasKey("Id");

                b.ToTable("Contacts");
            });
#pragma warning restore 612, 618
        }
    }
}
